// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    float4 currVal = Result[id.xy];
    float4 updatedVal = float4(1,1,1,1) - currVal;
    updatedVal.w = 1;
    Result[id.xy] = updatedVal;
}
